require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VisionboardsController do

  # This should return the minimal set of attributes required to create a valid
  # Visionboard. As you add validations to Visionboard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all visionboards as @visionboards" do
      visionboard = Visionboard.create! valid_attributes
      get :index
      assigns(:visionboards).should eq([visionboard])
    end
  end

  describe "GET show" do
    it "assigns the requested visionboard as @visionboard" do
      visionboard = Visionboard.create! valid_attributes
      get :show, :id => visionboard.id.to_s
      assigns(:visionboard).should eq(visionboard)
    end
  end

  describe "GET new" do
    it "assigns a new visionboard as @visionboard" do
      get :new
      assigns(:visionboard).should be_a_new(Visionboard)
    end
  end

  describe "GET edit" do
    it "assigns the requested visionboard as @visionboard" do
      visionboard = Visionboard.create! valid_attributes
      get :edit, :id => visionboard.id.to_s
      assigns(:visionboard).should eq(visionboard)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Visionboard" do
        expect {
          post :create, :visionboard => valid_attributes
        }.to change(Visionboard, :count).by(1)
      end

      it "assigns a newly created visionboard as @visionboard" do
        post :create, :visionboard => valid_attributes
        assigns(:visionboard).should be_a(Visionboard)
        assigns(:visionboard).should be_persisted
      end

      it "redirects to the created visionboard" do
        post :create, :visionboard => valid_attributes
        response.should redirect_to(Visionboard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved visionboard as @visionboard" do
        # Trigger the behavior that occurs when invalid params are submitted
        Visionboard.any_instance.stub(:save).and_return(false)
        post :create, :visionboard => {}
        assigns(:visionboard).should be_a_new(Visionboard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Visionboard.any_instance.stub(:save).and_return(false)
        post :create, :visionboard => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested visionboard" do
        visionboard = Visionboard.create! valid_attributes
        # Assuming there are no other visionboards in the database, this
        # specifies that the Visionboard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Visionboard.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => visionboard.id, :visionboard => {'these' => 'params'}
      end

      it "assigns the requested visionboard as @visionboard" do
        visionboard = Visionboard.create! valid_attributes
        put :update, :id => visionboard.id, :visionboard => valid_attributes
        assigns(:visionboard).should eq(visionboard)
      end

      it "redirects to the visionboard" do
        visionboard = Visionboard.create! valid_attributes
        put :update, :id => visionboard.id, :visionboard => valid_attributes
        response.should redirect_to(visionboard)
      end
    end

    describe "with invalid params" do
      it "assigns the visionboard as @visionboard" do
        visionboard = Visionboard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Visionboard.any_instance.stub(:save).and_return(false)
        put :update, :id => visionboard.id.to_s, :visionboard => {}
        assigns(:visionboard).should eq(visionboard)
      end

      it "re-renders the 'edit' template" do
        visionboard = Visionboard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Visionboard.any_instance.stub(:save).and_return(false)
        put :update, :id => visionboard.id.to_s, :visionboard => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested visionboard" do
      visionboard = Visionboard.create! valid_attributes
      expect {
        delete :destroy, :id => visionboard.id.to_s
      }.to change(Visionboard, :count).by(-1)
    end

    it "redirects to the visionboards list" do
      visionboard = Visionboard.create! valid_attributes
      delete :destroy, :id => visionboard.id.to_s
      response.should redirect_to(visionboards_url)
    end
  end

end
